### ISSUE TITLE
Only the last instance of an HTML node jme variable is visible

### ISSUE THREAD

**Issue by chrismgraham** [numbas/Numbas#731] opened 2020-08-28 11:44 UTC
When using a jme variable that is an HTML node, set up with e.g. html('<div>Text!</div>'), if the variable is used more than once, the node is only visible in the last instance. For example, if used in a statement and part prompt it will only appear in the latter, and if used in choices for an MCQ question, the variable only appears in the expected answers.

**Comment by christianp** [comment] 2020-10-08 11:59
I think this just needs to be documented, or it should throw an error on subsequent use.

**Comment by christianp** [comment] 2022-08-08 13:46
This is a duplicate of #886

**Closed by christianp** 2022-08-08 13:46 UTC
Labels: To be aware of
