### ISSUE TITLE
Allow change of question name in sequential mode exams

### ISSUE THREAD

**Issue by dshearman** [numbas/Numbas#881] opened 2022-01-20 05:13 UTC
We are developing instructional materials which we would like to use the sequestional mode navigation for (so that navigation is always visible) but don't want each section to be called "Question X". Would it be possible to allow the question names to be displayed as in menu mode exams? It would also be an advantage to rename the "End Exam" button to something like "End Session" or just "End".

**Comment by adellecolbourn** [comment] 2022-02-27 21:51
Allowing the question names in sequential mode to be something other than Question 1, Question 2 etc would also be helpful for me. I am using numbas to write practice materials for a numeracy test where the questions are not named numerically, but rather thematically eg 'At the Cafe', 'Tax time' etc.

**Comment by christianp** [comment] 2022-09-29 12:01
This is a duplicate of #852. You can now change the names of questions in sequential mode.

**Closed by christianp** 2022-09-29 12:01 UTC
Labels: Wishlist
