### ISSUE TITLE
SCORM exam in moodle loading fail

### ISSUE THREAD

**Issue by joshualim** [numbas/Numbas#624] opened 2019-06-18 10:15 UTC
When downloading new SCORM instances of an exam (e.g. https://numbas.mathcentre.ac.uk/exam/1973/numbas-website-demo/) and uploading to Moodle (tested under version 3.3 and 3.5) I get the error message below when running the package as "Preview" or "Normal". Old (<4.0) NUMBAS scorm packages run without issue. This is only an issue for exams, downloaded questions (e.g. https://numbas.mathcentre.ac.uk/question/8271/numbas-demo-jme-part/) load fine in moodle.

`Numbas has failed
Sorry, Numbas has encountered an error which means it can't continue. Below is a description of the error.`

`TypeError: Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
at https://moodle.bath.ac.uk/pluginfile.php/1363603/mod_scorm/content/4/scripts.js:11204:34
at Array.forEach ()
at Exam.makeQuestionList (https://moodle.bath.ac.uk/pluginfile.php/1363603/mod_scorm/content/4/scripts.js:11201:30)
at task (https://moodle.bath.ac.uk/pluginfile.php/1363603/mod_scorm/content/4/scripts.js:32687:25)
at pop (https://moodle.bath.ac.uk/pluginfile.php/1363603/mod_scorm/content/4/scripts.js:32711:13)
Created using Numbas, developed by Newcastle University.`

**Comment by christianp** [comment] 2019-06-20 08:46
@joshualim Thanks for reporting this. What browser were you using?

**Comment by christianp** [comment] 2019-06-20 08:46
@joshualim Thanks for reporting this. What browser were you using?

**Comment by joshualim** [comment] 2019-06-20 10:11
Chrome and Firefox (not sure on the versions as I'm away from my computer
today).

**Comment by christianp** [comment] 2020-03-26 15:51
I'm closing this because I can't reproduce it

**Closed by christianp** 2020-03-26 15:51 UTC
